// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwx-6k_EtmqoRtUDbSUjSSEZl4Fa-jmbc',
    appId: '1:775105476183:web:bb19625d3c311b630a1512',
    messagingSenderId: '775105476183',
    projectId: 'firstapp239',
    authDomain: 'firstapp239.firebaseapp.com',
    storageBucket: 'firstapp239.appspot.com',
    measurementId: 'G-RKZN5Q81HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8QlMbxWE9b2V44WoRVLbnJMK4Pgc3qzM',
    appId: '1:775105476183:android:f4b65fed9f5610e50a1512',
    messagingSenderId: '775105476183',
    projectId: 'firstapp239',
    storageBucket: 'firstapp239.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-Wm-96Lq74qHp9R6DyRnQVT5pZFA-sY',
    appId: '1:775105476183:ios:9636b5e2695310ba0a1512',
    messagingSenderId: '775105476183',
    projectId: 'firstapp239',
    storageBucket: 'firstapp239.appspot.com',
    iosBundleId: 'com.example.firstFbase239',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-Wm-96Lq74qHp9R6DyRnQVT5pZFA-sY',
    appId: '1:775105476183:ios:a0c806d2b38cc5f00a1512',
    messagingSenderId: '775105476183',
    projectId: 'firstapp239',
    storageBucket: 'firstapp239.appspot.com',
    iosBundleId: 'com.example.firstFbase239.RunnerTests',
  );
}
